import React, { useState } from 'react';
import { jsPDF } from 'jspdf';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, BorderStyle, WidthType } from 'docx';
import * as XLSX from 'xlsx';
import { FileText, Table as TableIcon, Check, FileSpreadsheet, Download, Loader2, RefreshCw, AlertTriangle } from 'lucide-react';
import { motion } from 'motion/react';
import { toast } from 'sonner';
import { saveAs } from 'file-saver';

interface DocumentExportCardProps {
  jsonData: string;
  isPro?: boolean;
}

export const DocumentExportCard: React.FC<DocumentExportCardProps> = ({ jsonData, isPro = false }) => {
  const [isGenerating, setIsGenerating] = useState<string | null>(null);
  const [parseError, setParseError] = useState<boolean>(false);
  const [parsedData, setParsedData] = useState<any | null>(null);

  // Lazy parse the data safely
  React.useEffect(() => {
    try {
      // Find JSON bounds in case LLM added extra markdown text around it
      let jsonStr = jsonData.trim();
      const firstCurly = jsonStr.indexOf('{');
      const lastCurly = jsonStr.lastIndexOf('}');
      if (firstCurly !== -1 && lastCurly !== -1) {
        jsonStr = jsonStr.substring(firstCurly, lastCurly + 1);
      }
      const data = JSON.parse(jsonStr);
      setParsedData(data);
      setParseError(false);
    } catch (e) {
      console.error("Failed to parse JSON file data:", e);
      setParseError(true);
    }
  }, [jsonData]);

  if (parseError) {
    return (
      <div className="my-4 p-4 bg-amber-500/10 border border-amber-500/20 rounded-2xl flex items-start gap-3 max-w-full">
        <AlertTriangle className="w-5 h-5 text-amber-500 shrink-0 mt-0.5" />
        <div>
          <h4 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">Document Blueprint Format Warning</h4>
          <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1">
            The AI drafted a document structure, but there is a formatting issue in the raw code blueprint. You can ask Trelvix to regenerate it.
          </p>
        </div>
      </div>
    );
  }

  if (!parsedData) {
    return (
      <div className="my-4 p-5 border border-zinc-200 dark:border-zinc-850 bg-zinc-50 dark:bg-zinc-900/40 rounded-2xl flex items-center justify-center gap-3">
        <Loader2 className="w-4 h-4 text-emerald-500 animate-spin" />
        <span className="text-xs text-zinc-400">Loading document export panel...</span>
      </div>
    );
  }

  const { fileType = "pdf", fileName = "trelvix-export", title = "Trelvix AI Document", subtitle, author = "Trelvix AI", sections = [] } = parsedData;

  const getCleanFilename = (ext: string) => {
    const clean = fileName
      .toLowerCase()
      .trim()
      .replace(/[^a-z0-9\s-_]/gi, '')
      .replace(/\s+/g, '_');
    return `${clean || 'trelvix-file'}.${ext}`;
  };

  // 1. PDF Export logic
  const handleExportPDF = async () => {
    setIsGenerating("pdf");
    toast.info("Assembling PDF typography and sections...");

    // Tiny artificial timeout for highly crafted, premium feel
    await new Promise(resolve => setTimeout(resolve, 800));

    try {
      const doc = new jsPDF();
      const pageHeight = doc.internal.pageSize.height;
      const pageWidth = doc.internal.pageSize.width;
      const margin = 20;
      const contentWidth = pageWidth - margin * 2;
      let y = 20;

      // Primary tracking page footer
      const drawPageFooter = () => {
        const totalPages = doc.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
          doc.setPage(i);
          
          // Draw faint divider line above footers
          doc.setDrawColor(243, 244, 246);
          doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);

          if (!isPro) {
            doc.setFont("Helvetica", "oblique");
            doc.setFontSize(8);
            doc.setTextColor(156, 163, 175);
            doc.text("Generated by Trelvix AI Document Engine", margin, pageHeight - 10);
          }
          doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin - 15, pageHeight - 10);
        }
      };

      // Header margin checker
      const checkPageOverflow = (neededHeight: number) => {
        if (y + neededHeight > pageHeight - margin - 15) {
          doc.addPage();
          y = margin;
          
          // Reprint secondary page badge
          doc.setFillColor(16, 185, 129);
          doc.rect(margin, y, 4, 4, "F");
          doc.setFont("Helvetica", "bold");
          doc.setFontSize(8);
          doc.setTextColor(107, 114, 128);
          doc.text(title.toUpperCase().substring(0, 31) + " | Continued", margin + 7, y + 3.5);
          y += 12;
        }
      };

      const drawParagraph = (text: string, fontSize = 10, fontStyle = 'normal') => {
        doc.setFont("Helvetica", fontStyle);
        doc.setFontSize(fontSize);
        doc.setTextColor(75, 85, 99);
        const lines = doc.splitTextToSize(text, contentWidth);
        const height = lines.length * (fontSize * 0.45) + 3;
        checkPageOverflow(height);
        doc.text(lines, margin, y);
        y += height;
      };

      // Top Header Line Tint
      doc.setFillColor(16, 185, 129); // Accent emerald
      doc.rect(margin, y, contentWidth, 3.5, "F");
      y += 11;

      // Main title banner
      doc.setFont("Helvetica", "bold");
      doc.setFontSize(22);
      doc.setTextColor(17, 24, 39);
      const titleLines = doc.splitTextToSize(title, contentWidth);
      doc.text(titleLines, margin, y);
      y += titleLines.length * 9.5 + 2;

      // Meta Header Subtitle
      if (subtitle || author) {
        doc.setFont("Helvetica", "normal");
        doc.setFontSize(9.5);
        doc.setTextColor(107, 114, 128);
        const subtitleStr = [subtitle, author ? `By: ${author}` : ''].filter(Boolean).join("  •  ");
        doc.text(subtitleStr, margin, y);
        y += 8;
      }

      // Border Divider Page Section
      doc.setDrawColor(229, 231, 235);
      doc.setLineWidth(0.5);
      doc.line(margin, y, pageWidth - margin, y);
      y += 12;

      // Draw all sections
      if (sections && Array.isArray(sections)) {
        sections.forEach((section: any) => {
          // 1. Title head
          if (section.heading) {
            checkPageOverflow(16);
            doc.setFont("Helvetica", "bold");
            doc.setFontSize(13);
            doc.setTextColor(17, 24, 39);
            doc.text(section.heading, margin, y);
            y += 6;

            // Header color trace underline
            doc.setDrawColor(16, 185, 129);
            doc.setLineWidth(0.75);
            doc.line(margin, y, margin + 20, y);
            y += 8;
          }

          // 2. Types
          if (section.type === "bullet" && Array.isArray(section.bullets)) {
            section.bullets.forEach((bullet: string) => {
              checkPageOverflow(7.5);
              doc.setFont("Helvetica", "normal");
              doc.setFontSize(10.5);
              doc.setTextColor(55, 65, 81);
              
              // Draw a tiny bullet point
              doc.setFillColor(156, 163, 175);
              doc.circle(margin + 2, y - 3, 1, "F");

              const bulletLines = doc.splitTextToSize(bullet, contentWidth - 8);
              doc.text(bulletLines, margin + 7, y);
              y += bulletLines.length * 5 + 2.5;
            });
            y += 4;
          } else if (section.type === "table" && Array.isArray(section.headers) && Array.isArray(section.rows)) {
            const headers = section.headers;
            const rows = section.rows;
            const colWidth = contentWidth / headers.length;
            const rHeight = 8.5;

            // Render header columns
            checkPageOverflow(rHeight + 5);
            doc.setFillColor(55, 65, 81); // beautiful dark slate header backgrounds
            doc.rect(margin, y, contentWidth, rHeight, "F");

            doc.setFont("Helvetica", "bold");
            doc.setFontSize(9);
            doc.setTextColor(255, 255, 255);
            doc.setDrawColor(209, 213, 219);
            doc.setLineWidth(0.25);

            headers.forEach((hdr: string, i: number) => {
              const cellX = margin + i * colWidth;
              const safeText = hdr.length > 20 ? hdr.substring(0, 18) + ".." : hdr;
              doc.text(safeText, cellX + 3.5, y + 5.5);
              doc.line(cellX, y, cellX, y + rHeight);
            });
            // Outer boundaries border lines
            doc.line(margin + contentWidth, y, margin + contentWidth, y + rHeight);
            doc.line(margin, y, margin + contentWidth, y);
            doc.line(margin, y + rHeight, margin + contentWidth, y + rHeight);
            y += rHeight;

            // Rows with alternating stripes
            rows.forEach((rowArr: any[], rIdx: number) => {
              checkPageOverflow(rHeight + 2);
              if (rIdx % 2 === 1) {
                doc.setFillColor(249, 250, 251); // row stripe tint
                doc.rect(margin, y, contentWidth, rHeight, "F");
              }

              doc.setFont("Helvetica", "normal");
              doc.setFontSize(8.5);
              doc.setTextColor(75, 85, 99);

              rowArr.forEach((cellVal: any, cIdx: number) => {
                const cellX = margin + cIdx * colWidth;
                const cellStr = String(cellVal ?? "");
                const safeValText = cellStr.length > 25 ? cellStr.substring(0, 22) + "..." : cellStr;
                doc.text(safeValText, cellX + 3.5, y + 5.5);
                doc.line(cellX, y, cellX, y + rHeight);
              });
              doc.line(margin + contentWidth, y, margin + contentWidth, y + rHeight);
              doc.line(margin, y + rHeight, margin + contentWidth, y + rHeight);
              y += rHeight;
            });
            y += 8;
          } else if (Array.isArray(section.paragraphs)) {
            section.paragraphs.forEach((p: string) => {
              drawParagraph(p, 10.5, 'normal');
            });
            y += 4;
          }
        });
      }

      // Apply complete footnoting structure onto all pages built
      drawPageFooter();

      // Download trigger
      const pdfBlob = doc.output('blob');
      saveAs(pdfBlob, getCleanFilename("pdf"));
      toast.success("PDF generated successfully!");
    } catch (err) {
      console.error(err);
      toast.error("Failed to compile PDF document.");
    } finally {
      setIsGenerating(null);
    }
  };

  // 2. DOCX Word Export logic
  const handleExportDOCX = async () => {
    setIsGenerating("docx");
    toast.info("Drafting Word document structure...");

    await new Promise(resolve => setTimeout(resolve, 800));

    try {
      const docChildren: any[] = [];

      // Big Title Header
      docChildren.push(
        new Paragraph({
          heading: HeadingLevel.TITLE,
          spacing: { after: 150, before: 100 },
          children: [
            new TextRun({
              text: title,
              bold: true,
              size: 34,
              color: "1F2937", // Grey-805
              font: "Arial",
            }),
          ],
        })
      );

      // Metas
      if (subtitle || author) {
        const subStr = [subtitle, author ? `Author: ${author}` : ''].filter(Boolean).join("  |  ");
        docChildren.push(
          new Paragraph({
            spacing: { after: 250 },
            children: [
              new TextRun({
                text: subStr,
                italics: true,
                size: 19,
                color: "6B7280",
                font: "Arial",
              }),
            ],
          })
        );
      }

      // Add a line break
      docChildren.push(new Paragraph({ spacing: { after: 150 } }));

      // Sections mapping
      if (sections && Array.isArray(sections)) {
        sections.forEach((section: any) => {
          if (section.heading) {
            docChildren.push(
              new Paragraph({
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 200, after: 100 },
                children: [
                  new TextRun({
                    text: section.heading,
                    bold: true,
                    size: 26,
                    color: "10B981", // Emerald accent
                    font: "Arial",
                  }),
                ],
              })
            );
          }

          if (section.type === "bullet" && Array.isArray(section.bullets)) {
            section.bullets.forEach((bulletItem: string) => {
              docChildren.push(
                new Paragraph({
                  bullet: { level: 0 },
                  spacing: { after: 60 },
                  children: [
                    new TextRun({
                      text: bulletItem,
                      size: 21,
                      color: "374151",
                      font: "Arial",
                    }),
                  ],
                })
              );
            });
            docChildren.push(new Paragraph({ spacing: { after: 60 } }));
          } else if (section.type === "table" && Array.isArray(section.headers) && Array.isArray(section.rows)) {
            const headers = section.headers;
            const rows = section.rows;

            const tWidth = 100 / headers.length;

            const tableRows = [
              // Styled Table Header
              new TableRow({
                children: headers.map((hdrStr: string) => (
                  new TableCell({
                    width: { size: tWidth, type: WidthType.PERCENTAGE },
                    shading: { fill: "374151", color: "auto" }, // Dark header shading
                    margins: { top: 120, bottom: 120, left: 160, right: 160 },
                    children: [
                      new Paragraph({
                        children: [
                          new TextRun({
                            text: hdrStr,
                            bold: true,
                            size: 19,
                            color: "FFFFFF",
                            font: "Arial",
                          }),
                        ],
                      }),
                    ],
                  })
                )),
              }),

              // Table Body Data Items
              ...rows.map((rowArr: any[], rId: number) => (
                new TableRow({
                  children: rowArr.map((cellObj: any) => (
                    new TableCell({
                      width: { size: tWidth, type: WidthType.PERCENTAGE },
                      shading: rId % 2 === 1 ? { fill: "F9FAFB", color: "auto" } : undefined, // alternating background sheets
                      margins: { top: 110, bottom: 110, left: 160, right: 160 },
                      children: [
                        new Paragraph({
                          children: [
                            new TextRun({
                              text: String(cellObj ?? ""),
                              size: 19,
                              color: "4B5563",
                              font: "Arial",
                            }),
                          ],
                        }),
                      ],
                    })
                  )),
                })
              )),
            ];

            docChildren.push(
              new Table({
                width: { size: 100, type: WidthType.PERCENTAGE },
                margins: { top: 120, bottom: 120, left: 160, right: 160 },
                borders: {
                  top: { style: BorderStyle.SINGLE, size: 4, color: "E5E7EB" },
                  bottom: { style: BorderStyle.SINGLE, size: 4, color: "E5E7EB" },
                  left: { style: BorderStyle.SINGLE, size: 4, color: "E5E7EB" },
                  right: { style: BorderStyle.SINGLE, size: 4, color: "E5E7EB" },
                  insideHorizontal: { style: BorderStyle.SINGLE, size: 4, color: "E5E7EB" },
                  insideVertical: { style: BorderStyle.SINGLE, size: 4, color: "E5E7EB" },
                },
                rows: tableRows,
              })
            );

            // Spacing spacer after table
            docChildren.push(new Paragraph({ spacing: { after: 120 } }));
          } else if (Array.isArray(section.paragraphs)) {
            section.paragraphs.forEach((pStr: string) => {
              docChildren.push(
                new Paragraph({
                  spacing: { after: 150 },
                  children: [
                    new TextRun({
                      text: pStr,
                      size: 21,
                      color: "374151",
                      font: "Arial",
                    }),
                  ],
                })
              );
            });
            docChildren.push(new Paragraph({ spacing: { after: 50 } }));
          }
        });
      }

      // Core wrapper
      const wordDocument = new Document({
        sections: [{
          properties: {},
          children: docChildren,
        }],
      });

      const blobOut = await Packer.toBlob(wordDocument);
      saveAs(blobOut, getCleanFilename("docx"));

      toast.success("Word Document exported successfully!");
    } catch (e) {
      console.error(e);
      toast.error("Failed to construct Microsoft Word document.");
    } finally {
      setIsGenerating(null);
    }
  };

  // 3. XLSX Excel Spreadsheet Export logic
  const handleExportXLSX = async () => {
    setIsGenerating("xlsx");
    toast.info("Generating spreadsheet cells and worksheets...");

    await new Promise(resolve => setTimeout(resolve, 800));

    try {
      const workbook = XLSX.utils.book_new();
      let addedWorksheet = false;

      // Check if structured workbook spreadsheet data block exists
      if (parsedData.spreadsheet && Array.isArray(parsedData.spreadsheet.sheets)) {
        parsedData.spreadsheet.sheets.forEach((sheet: any) => {
          if (sheet.name && Array.isArray(sheet.rows)) {
            const worksheet = XLSX.utils.aoa_to_sheet(sheet.rows);
            // Limit sheet name length to Excel limit (31)
            XLSX.utils.book_append_sheet(workbook, worksheet, sheet.name.substring(0, 31));
            addedWorksheet = true;
          }
        });
      }

      // Check sections for table occurrences and output them as excel sheet tabs
      if (sections && Array.isArray(sections)) {
        sections.forEach((section: any, id: number) => {
          if (section.type === "table" && Array.isArray(section.headers) && Array.isArray(section.rows)) {
            const gridData = [section.headers, ...section.rows];
            const worksheet = XLSX.utils.aoa_to_sheet(gridData);
            const sheetTitle = (section.heading || `Table ${id + 1}`).substring(0, 31);
            XLSX.utils.book_append_sheet(workbook, worksheet, sheetTitle);
            addedWorksheet = true;
          }
        });
      }

      // Fallback: If document has NO databases/tables, write standard report content into a flat rows scheme
      if (!addedWorksheet) {
        const flatContent: any[][] = [
          [title],
          [subtitle || ""],
          ["Author", author],
          [""],
          ["DOCUMENT STRUCTURAL SECTION LOGS"],
        ];

        if (sections && Array.isArray(sections)) {
          sections.forEach((sec: any) => {
            if (sec.heading) {
              flatContent.push([""]);
              flatContent.push([sec.heading.toUpperCase()]);
            }
            if (sec.type === "bullet" && Array.isArray(sec.bullets)) {
              sec.bullets.forEach((bulletStr: string) => {
                flatContent.push([`• ${bulletStr}`]);
              });
            } else if (Array.isArray(sec.paragraphs)) {
              sec.paragraphs.forEach((pStr: string) => {
                flatContent.push([pStr]);
              });
            }
          });
        }

        const fallbackWorksheet = XLSX.utils.aoa_to_sheet(flatContent);
        XLSX.utils.book_append_sheet(workbook, fallbackWorksheet, "Export Overview");
      }

      // Export file
      const writeBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
      const excelBlob = new Blob([writeBuffer], { type: 'application/octet-stream' });
      saveAs(excelBlob, getCleanFilename("xlsx"));
      toast.success("Excel spreadsheet exported successfully!");
    } catch (exc) {
      console.error(exc);
      toast.error("Failed to construct Excel workbook.");
    } finally {
      setIsGenerating(null);
    }
  };

  // Determine which format is requested and should be rendered
  const reqType = String(fileType || '').toLowerCase().trim();
  const hasSpreadsheetData = parsedData.spreadsheet || sections?.some((s: any) => s.type === 'table');
  
  const showExcel = reqType === "xlsx" || reqType === "excel" || reqType === "spreadsheet" || (reqType === "" && hasSpreadsheetData);
  const showWord = reqType === "docx" || reqType === "doc" || reqType === "word";
  const showPDF = reqType === "pdf" || (!showExcel && !showWord);

  const fileExtLabel = showExcel 
    ? "Excel Spreadsheet (.xlsx)" 
    : (showWord ? "Microsoft Word (.docx)" : "PDF Document (.pdf)");

  return (
    <motion.div 
      initial={{ opacity: 0, scale: 0.98, y: 12 }} 
      animate={{ opacity: 1, scale: 1, y: 0 }}
      transition={{ duration: 0.4, ease: "easeOut" }}
      className="my-6 rounded-2xl border border-zinc-200/80 dark:border-zinc-800/80 bg-white dark:bg-zinc-950 overflow-hidden shadow-lg hover:shadow-xl transition-all duration-350 max-w-full w-full"
    >
      {/* Top Header Card Area */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 p-5 md:p-6 border-b border-zinc-150 dark:border-zinc-800 bg-zinc-50/50 dark:bg-zinc-900/20 backdrop-blur-md min-w-0 w-full">
        <div className="flex items-start gap-3 md:gap-4 min-w-0 flex-1 w-full">
          <div className="w-10 h-10 md:w-12 md:h-12 rounded-xl md:rounded-2xl bg-zinc-900 dark:bg-white text-white dark:text-zinc-950 flex items-center justify-center shrink-0 shadow-md">
            {showExcel ? <FileSpreadsheet className="w-5 h-5 md:w-6 md:h-6 text-emerald-500" /> : <FileText className="w-5 h-5 md:w-6 md:h-6 text-emerald-500" />}
          </div>
          <div className="min-w-0 flex-1">
            <h4 className="text-sm md:text-base font-bold text-zinc-900 dark:text-zinc-50 leading-snug tracking-tight font-sans break-words pr-1">
              {title}
            </h4>
            <div className="flex flex-wrap items-center gap-1.5 mt-1 min-w-0">
              <span className="text-[8px] md:text-[9px] font-bold text-zinc-500 dark:text-zinc-400 uppercase tracking-widest bg-zinc-100 dark:bg-zinc-800/60 px-1.5 py-0.5 rounded border border-zinc-200/50 dark:border-zinc-700/50 shrink-0">
                Document Export Center
              </span>
              <span className="text-[11px] md:text-xs font-semibold text-emerald-600 dark:text-emerald-400 break-words">
                Type: {fileExtLabel}
              </span>
            </div>
          </div>
        </div>

        {/* Short outline statistics indicator */}
        <div className="text-xs font-mono text-zinc-400 dark:text-zinc-500 border-l md:border-l-0 md:pl-0 pl-4 border-zinc-200 dark:border-zinc-800 flex flex-col md:items-end shrink-0">
          <span className="font-semibold text-zinc-750 dark:text-zinc-300">Outline: {sections?.length || 0} structures</span>
          <span>By: {author || "Trelvix AI"}</span>
        </div>
      </div>

      {/* Button exports selector group - rendered professionally and minimalistically */}
      <div className="p-5 md:p-8 flex flex-col items-center justify-center text-center bg-gradient-to-b from-transparent to-zinc-50/30 dark:to-zinc-950/20 w-full">
        <div className="max-w-md w-full mb-5">
          <p className="text-xs md:text-sm text-zinc-500 dark:text-zinc-400 leading-relaxed break-words">
            Your document has been compiled and formatted successfully based on your request. Below, you can export the production-ready file to your local computer.
          </p>
        </div>

        <div className="w-full max-w-sm flex flex-col gap-2.5">
          {/* PDF Document Button */}
          {showPDF && (
            <motion.button
              whileHover={{ scale: 1.01 }}
              whileTap={{ scale: 0.99 }}
              onClick={handleExportPDF}
              disabled={isGenerating !== null}
              className="w-full py-3 md:py-3.5 px-4 md:px-6 rounded-xl md:rounded-2xl flex items-center justify-center gap-2 bg-zinc-950 hover:bg-zinc-900 dark:bg-zinc-50 dark:hover:bg-zinc-150 text-white dark:text-zinc-950 active:scale-[0.98] transition-all cursor-pointer font-semibold text-xs md:text-sm disabled:opacity-40 disabled:pointer-events-none disabled:active:scale-100 shadow-md md:shadow-lg shadow-zinc-950/10 dark:shadow-none border border-zinc-900 dark:border-zinc-200"
            >
              {isGenerating === "pdf" ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 animate-spin text-emerald-500 shrink-0" />
                  <span className="break-words">Compiling PDF document...</span>
                </>
              ) : (
                <>
                  <Download className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
                  <span className="break-words">Download PDF Document</span>
                </>
              )}
            </motion.button>
          )}

          {/* Word Document Button */}
          {showWord && (
            <motion.button
              whileHover={{ scale: 1.01 }}
              whileTap={{ scale: 0.99 }}
              onClick={handleExportDOCX}
              disabled={isGenerating !== null}
              className="w-full py-3 md:py-3.5 px-4 md:px-6 rounded-xl md:rounded-2xl flex items-center justify-center gap-2 bg-zinc-950 hover:bg-zinc-900 dark:bg-zinc-50 dark:hover:bg-zinc-150 text-white dark:text-zinc-950 active:scale-[0.98] transition-all cursor-pointer font-semibold text-xs md:text-sm disabled:opacity-40 disabled:pointer-events-none disabled:active:scale-100 shadow-md md:shadow-lg shadow-zinc-950/10 dark:shadow-none border border-zinc-900 dark:border-zinc-200"
            >
              {isGenerating === "docx" ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 animate-spin text-emerald-500 shrink-0" />
                  <span className="break-words">Compiling Word Document...</span>
                </>
              ) : (
                <>
                  <FileText className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
                  <span className="break-words">Download Word Document</span>
                </>
              )}
            </motion.button>
          )}

          {/* Excel Workbook Button */}
          {showExcel && (
            <motion.button
              whileHover={{ scale: 1.01 }}
              whileTap={{ scale: 0.99 }}
              onClick={handleExportXLSX}
              disabled={isGenerating !== null}
              className="w-full py-3 md:py-3.5 px-4 md:px-6 rounded-xl md:rounded-2xl flex items-center justify-center gap-2 bg-zinc-950 hover:bg-zinc-900 dark:bg-zinc-50 dark:hover:bg-zinc-150 text-white dark:text-zinc-950 active:scale-[0.98] transition-all cursor-pointer font-semibold text-xs md:text-sm disabled:opacity-40 disabled:pointer-events-none disabled:active:scale-100 shadow-md md:shadow-lg shadow-zinc-950/10 dark:shadow-none border border-zinc-900 dark:border-zinc-200"
            >
              {isGenerating === "xlsx" ? (
                <>
                  <Loader2 className="w-3.5 h-3.5 animate-spin text-emerald-500 shrink-0" />
                  <span className="break-words">Compiling Excel Spreadsheet...</span>
                </>
              ) : (
                <>
                  <TableIcon className="w-3.5 h-3.5 text-emerald-500 shrink-0" />
                  <span className="break-words">Download Excel Spreadsheet</span>
                </>
              )}
            </motion.button>
          )}
        </div>
      </div>

      {/* Under footer disclaimer */}
      <div className="px-5 py-3 bg-zinc-50 dark:bg-zinc-900/30 border-t border-zinc-150 dark:border-zinc-800/40 text-[10px] text-zinc-400 dark:text-zinc-500 flex items-center justify-between font-mono">
        <span>Trelvix Document Compiler v2.1.0</span>
        <span>Secure Sandbox Export</span>
      </div>
    </motion.div>
  );
};
